appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure:
    BINSTAR_TOKEN: Jj8dUhAwncB6I3WuSe+rcDh+XtCUEQuWq/YbnUj0JxgxLSi80Ip6c3wtqgcQ/NzOX9IGg57cobN8Aq9IpB81uQQJkfnh0DSU22z40r2uyxxwKS8txU6VL4SNwTSU3iSXfDbBGEwY3zKNK55+L9I1N2MTY40Qz6HkC4L3hboqX96WnAZAnTZ1PPCLdasIXEBftlLSJLiowY5clT0SgQaHBKOYftMhfNpR5VhlTWRd9mBQimteZyPyZYGlokCxaTLfvmvDG2mcL7v03R5/HTw2kPuZW1tMlN839Z2vVLKq7uxi1u9TP8FY6w6kdwkrnZ2NEXqbyiCeDFEufOp21Sc796BzhqIdPXUT45/1NVNJ9ntM4t5YdxFvWDbrAtJdekVlQzOR5tZLmuGdcv20NPl+LGUcdkJ0tzaS1/hdrECtXjQuKQgK6Dh93nHtJ6VmHK97ubTVydE8hCijK3SqnqDql9JRcBnUsYSv98md7EzG9hhZNVr8qucQ45yab0/AeeHcS8hbIjpt+jWs8TSkhpAGh6Kph9kUwxc8BXkAR1LNB6ezyIAOL4tcVIzf38Y9a2tJpnUbeTPw3Q+lynRdCVXQS4pKKubN9A4fEWz1gIOsTpMGdFCYbnKc+MUgB7yMxS6JNxaovLXXsEse+U5HvVI3PW28Ky5rDcZLvVzk7m2c4yg=
